### ISSUE TITLE
segfault in argparser

### ISSUE THREAD

**Issue by arnd** [flowgrind/flowgrind#177]
Starting program: /home/arnd/umic-mesh/clean/flowgrind/flowgrind -n2 -F 0  -H s=127.0.0.1,d=127.0.0.1  -F 1 s=127.0.0.2,d=127.0.0.2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
ap_check_mutex (ap=0x135adc0 <parser>, ms=<optimized out>, i=<optimized out>, conflict=0x7fffffffad1c) at src/fg_argparser.c:538
warning: Source file is more recent than executable.
538	
(gdb) bt
#0  ap_check_mutex (ap=0x135adc0 <parser>, ms=<optimized out>, i=<optimized out>, conflict=0x7fffffffad1c) at src/fg_argparser.c:538
#1  0x000000000040bd94 in ap_set_check_mutex (ap=ap@entry=0x135adc0 <parser>, ms=ms@entry=0x7fffffffad60, i=i@entry=4, conflict=conflict@entry=0x7fffffffad1c) at src/fg_argparser.c:570
#2  0x000000000040a620 in check_mutex (flow_id=0, argind=4, context=MUTEX_CONTEXT_CONTROLLER, ms=0x7fffffffad60) at src/flowgrind.c:2575
#3  parse_cmdline (argc=argc@entry=9, argv=argv@entry=0x7fffffffdc78) at src/flowgrind.c:2721
#4  0x00000000004022e7 in main (argc=9, argv=0x7fffffffdc78) at src/flowgrind.c:2889

**Comment by arnd** [comment]
Bug seems to be fixed in current next HEAD:

./flowgrind -n2 -F 0 -H s=127.0.0.1,d=127.0.0.1 -F 1 s=127.0.0.2,d=127.0.0.2
flowgrind: error: invalid argument: s=127.0.0.2,d=127.0.0.2
Try 'flowgrind -h' for more information
